# Usa la imagen base de Tomcat
FROM tomcat:9.0

# Copia el archivo .war en el directorio webapps de Tomcat
COPY retroinventario.war /usr/local/tomcat/webapps/

# Configura las variables de entorno para la base de datos
ENV DB_URL=jdbc:mysql://mysql://root:BpsjBXZHmZNSmhXssdpGSyJnDkTwHeEQ@monorail.proxy.rlwy.net:56334/railway/retroinventario
ENV DB_USERNAME=root
ENV DB_PASSWORD=BpsjBXZHmZNSmhXssdpGSyJnDkTwHeEQ

# Exponer el puerto 8080
EXPOSE 8080
